### ISSUE TITLE
APRS filters

### ISSUE THREAD

**Issue by Fiddich** [Turbo87/actix-ogn#21]
Hi,

I am trying to adapt the code (and to learn Rust while doing this...)
What I dont understand, I set a usrname and password, this works.

But also adding an APRS filter to limit to a region, it never gets used.
Any idea?

```rust
                    let login_message = { 
.....
                        let box_filter = "a/52/2/49/7";

                        format!(
                            "user {} pass {} vers {} {} filter {}",
                            username,
                            password,
                            app_name,
                            app_version,
                            box_filter
                        )
                    };
```

**Comment by Turbo87** [comment]
hmm, I've never used this with a filter so far, sorry 😞

**Comment by Fiddich** [comment]
Yeah, but do you have any idea why the filter - the value - is not passing ? The format is normally right.....

**Comment by Turbo87** [comment]
> do you have any idea why the filter - the value - is not passing ?

nope, sorry
